baseURL = "https://example.com/"
languageCode = "en-us"
title = "Flying Worx"
enableRobotsTXT = true
copyright = "© {{ now.Year }} Flying Worx"

[pagination]
  pagerSize = 10

[params]
  description = "Flying Worx site built with Hugo"
  author = "Flying Worx"
  github = "https://github.com/tbrown1967"

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[outputs]
  home = ["HTML", "RSS"]

[menus]
  [[menus.main]]
    name = "Home"
    pageRef = "/"
    weight = 1
  [[menus.main]]
    name = "Posts"
    pageRef = "/posts"
    weight = 2

[taxonomies]
  category = "categories"
  tag = "tags"
