site_name: FlyingWorx-Instrument-Training
site_url: https://www.flyingworx.com/
site_author: Timothy Brown
repo_name: tbrown1967/flyingworx.com/FlyingWorx-Instrument-Training
repo_url: https://github.com/tbrown1967/flyingworx.com

theme:
  name: material
  palette:
    primary: 'indigo'
    accent: 'indigo'
  features:
    - content.code.copy
    - content.code.annotate

nav:
  - Home: index.md
  - Preflight Preparation:
      - Pilot Qualifications: docs/preflight/pilotqualifications.md
      - Weather Information: docs/preflight/weatherinformation.md
      - Cross Country Flight Planning: docs/preflight/flightplanning.md
  - Preflight Procedures:
      - Aircraft Systems Related to Instrument Flight Rules (IFR) Operations: docs/preflight/aircraftsystems.md
      - Aircraft Flight Instruments and Navigation Equipment: docs/preflight/flightinstruments.md
      - Instrument Flight Deck Check: docs/preflight/flightdeck.md
